name: Deployment Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
        folders: "/services/authentication /services/dashboard /services/user /services/driver"
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        id: docker-hub
        env:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u $username -p $password

      - name: Build docker image
        id: build-docker-image
        run: |
            for folder in ${{ env.folders }}; do
                docker build -t ${{secrets.DOCKER_HUB_USERNAME}}/$folder:latest $folder
            done